variables:
- name: storageContainer
  value: launchstorage1905692099
- name: serviceConnection
  value: 'ado-sp'
# trigger:
#   branches:
#     include:
#     - main
stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push'
    pool: 'container-pool'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.0.0'
        force32bit: false
        displayName: 'Install Node.js'
  # - task: NodeTool@0
  #   inputs:
  #     versionSpec: '10.x'
  #     displayName: 'Install Node.js'
    # - task: CmdLine@2
    #   displayName: npm install
    #   inputs:
    #     script: |
    #       npm install -g @angular/cli
    #       npm install
    # - task: CmdLine@2
    #   displayName: ng build
    #   inputs:
    #     script: |
    #       set PATH=%PATH%;%CD%\node_modules\.bin;C:\npm\prefix
    #       ng build --subresource-integrity --output-hashing none
    # - task: AzureFileCopy@2
    #   displayName: Deploy Files
    #   inputs:
    #     SourcePath: '$(System.DefaultWorkingDirectory)\dist\$(Build.Repository.Name)'
    #     azureSubscription: $(serviceConnection)
    #     Destination: 'AzureBlob'
    #     storage: $(storageContainer)
    #     ContainerName: '$web'
    #     BlobPrefix: ''
    # - task: AzureCLI@2
    #   displayName: Delete Old Files
    #   inputs:
    #     azureSubscription: $(serviceConnection)
    #     scriptType: 'pscore'
    #     scriptLocation: 'inlineScript'
    #     inlineScript: 'az storage blob delete-batch -s `$web --account-name $(storageContainer) --if-unmodified-since $(Get-Date ((Get-Date).addMinutes(-5)) -UFORMAT +%Y-%m-%dT%H:%MZ)'