variables:
- name: storageContainer
  value: launchstorage1905692099
- name: serviceConnection
  value: 'ado-sp'
# trigger:
#   branches:
#     include:
#     - main
stages:
- stage: BuildAndPush
  jobs:
  - job: BuildAndPush
    displayName: 'Build and Push'
    pool: 'container-pool'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.0.0'
        force32bit: false
        displayName: 'Install Node.js'
    - task: CmdLine@2
      displayName: npm install
      inputs:
        script: |
          npm config set legacy-peer-deps true
          npm install -g @angular/cli
          npm install
    - task: CmdLine@2
      displayName: ng build
      inputs:
        script: |
          npm run build
    - task: CmdLine@2
      displayName: install az-cli
      inputs:
        script: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | bash
          az --version
    
    - task: AzureCLI@2
      displayName: Upload files to container
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: inlineScript
        inlineScript: |
          pwd
          ls
          cd '$(System.DefaultWorkingDirectory)/dist'
          pwd
          ls
          az storage azcopy blob upload --container '$web' --account-name  $(storageContainer) --source '$(System.DefaultWorkingDirectory)/dist/*' --only-show-errors --recursive


    - task: AzureCLI@2
      displayName: Delete Old Files
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: az storage blob delete-batch -s '$web' --account-name $(storageContainer) --if-unmodified-since $(Get-Date ((Get-Date).addMinutes(-5)) -UFORMAT +%Y-%m-%dT%H:%MZ)